import { useMemo } from "react";
import { Alert, Image, Linking, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

import { ScreenContainer } from "@/components/screen-container";
import { useAppData } from "@/lib/app-store";
import { customerWhatsappMessage, customerWhatsappOverdueMessage, DEVICE_STATUSES, formatDate, isOverdue, remainingAmount, STATUS_COLORS, type DeviceRecord, type DeviceStatus } from "@/lib/app-types";

export default function DeviceDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { devices, updateStatus, archiveDevice } = useAppData();
  const device = useMemo(() => devices.find((item) => item.id === id), [devices, id]);
  if (!device) return <ScreenContainer><View style={styles.empty}><Text style={styles.title}>السجل غير موجود</Text><Pressable onPress={() => router.back()}><Text style={styles.link}>العودة</Text></Pressable></View></ScreenContainer>;
  const overdue = isOverdue(device);
  const update = async (status: DeviceStatus) => { await updateStatus(device.id, status); };
  const archive = () => Alert.alert("أرشفة السجل", "سيبقى السجل محفوظًا في الأرشيف ولن يظهر ضمن الأجهزة النشطة.", [{ text: "إلغاء", style: "cancel" }, { text: "أرشفة", style: "destructive", onPress: () => { void archiveDevice(device.id); router.back(); } }]);
  const whatsapp = async () => { if (!device.customerPhone) { Alert.alert("رقم غير موجود", "أضف رقم هاتف الزبون أولًا."); return; } const phone = device.customerPhone.replace(/[^0-9+]/g, ""); const message = overdue ? customerWhatsappOverdueMessage(device) : customerWhatsappMessage(device); await Linking.openURL(`whatsapp://send?phone=${phone}&text=${encodeURIComponent(message)}`); };
  const share = async () => { await Share.share({ message: `${device.orderNumber}\n${device.customerName}\n${device.deviceModel}\nالحالة: ${device.status}\nالمتبقي: ${remainingAmount(device).toLocaleString()} د.ع` }); };
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={22} color="#5F574D" /></Pressable><View style={styles.headerText}><Text style={styles.eyebrow}>{device.orderNumber}</Text><Text style={styles.title}>{device.deviceModel || device.deviceType}</Text><Text style={styles.subtitle}>{device.customerName} • {device.customerPhone || "بدون رقم"}</Text></View></View>
    <View style={styles.statusBanner}><View><Text style={styles.bannerLabel}>الحالة الحالية</Text><Text style={[styles.bannerStatus, { color: STATUS_COLORS[device.status] }]}>{device.status}</Text>{overdue && <Text style={styles.overdue}>هذا الجهاز متأخر عن موعد التسليم</Text>}</View><View style={[styles.statusCircle, { backgroundColor: `${STATUS_COLORS[device.status]}20` }]}><MaterialIcons name={device.status === "جاهز للتسليم" ? "check-circle" : "build"} size={28} color={STATUS_COLORS[device.status]} /></View></View>
    {device.imageUris.length > 0 && <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.photos}>{device.imageUris.map((uri) => <Image key={uri} source={{ uri }} style={styles.photo} />)}</ScrollView>}
    <View style={styles.actions}><Pressable onPress={() => void whatsapp()} style={styles.action}><MaterialIcons name="chat" size={19} color="#2E8B70" /><Text style={styles.actionText}>WhatsApp</Text></Pressable><Pressable onPress={() => void share()} style={styles.action}><MaterialIcons name="share" size={19} color="#9A661D" /><Text style={styles.actionText}>مشاركة</Text></Pressable><Pressable onPress={archive} style={styles.action}><MaterialIcons name="archive" size={19} color="#C25B56" /><Text style={styles.actionText}>أرشفة</Text></Pressable></View>
    <InfoGrid device={device} />
    <Text style={styles.sectionTitle}>تحديث الحالة</Text><View style={styles.statusGrid}>{DEVICE_STATUSES.map((status) => <Pressable key={status} onPress={() => void update(status)} style={[styles.statusButton, device.status === status && { borderColor: STATUS_COLORS[status], backgroundColor: `${STATUS_COLORS[status]}12` }]}><View style={[styles.dot, { backgroundColor: STATUS_COLORS[status] }]} /><Text style={styles.statusText}>{status}</Text></Pressable>)}</View>
    {device.notes ? <View style={styles.note}><Text style={styles.noteLabel}>ملاحظات</Text><Text style={styles.noteText}>{device.notes}</Text></View> : null}
  </ScrollView></ScreenContainer>;
}
function InfoGrid({ device }: { device: DeviceRecord }) { return <View style={styles.infoCard}><Info label="تاريخ الاستلام" value={formatDate(device.receivedAt)} /><Info label="التسليم المتوقع" value={formatDate(device.expectedDeliveryAt)} /><Info label="الإجمالي" value={`${device.totalAmount.toLocaleString()} د.ع`} /><Info label="المدفوع" value={`${device.paidAmount.toLocaleString()} د.ع`} /><Info label="المتبقي" value={`${remainingAmount(device).toLocaleString()} د.ع`} /><Info label="صور الجهاز" value={`${device.imageUris.length} صورة`} /></View>; }
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 36, gap: 15, direction: "rtl" }, header: { flexDirection: "row-reverse", alignItems: "center", gap: 12 }, back: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#FFF", borderWidth: 1, borderColor: "#E8E0D4", alignItems: "center", justifyContent: "center" }, headerText: { flex: 1, alignItems: "flex-end" }, eyebrow: { color: "#9A661D", fontSize: 12, fontWeight: "900" }, title: { color: "#1F2937", fontSize: 25, fontWeight: "900", marginTop: 3, textAlign: "right" }, subtitle: { color: "#80776B", fontSize: 12, marginTop: 4 }, statusBanner: { backgroundColor: "#FFF", borderWidth: 1, borderColor: "#EEE7DC", borderRadius: 20, padding: 17, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, bannerLabel: { color: "#8B8175", fontSize: 11, textAlign: "right" }, bannerStatus: { fontSize: 20, fontWeight: "900", marginTop: 4, textAlign: "right" }, statusCircle: { width: 56, height: 56, borderRadius: 19, alignItems: "center", justifyContent: "center" }, overdue: { color: "#C25B56", fontSize: 11, fontWeight: "700", marginTop: 5, textAlign: "right" }, photos: { flexDirection: "row-reverse", gap: 9 }, photo: { width: 112, height: 112, borderRadius: 16, backgroundColor: "#EEE" }, actions: { flexDirection: "row-reverse", gap: 9 }, action: { flex: 1, backgroundColor: "#FFF", borderWidth: 1, borderColor: "#EEE7DC", borderRadius: 14, paddingVertical: 12, alignItems: "center", gap: 4 }, actionText: { color: "#5F574D", fontSize: 11, fontWeight: "800" }, infoCard: { backgroundColor: "#FFF", borderWidth: 1, borderColor: "#EEE7DC", borderRadius: 18, padding: 14, flexDirection: "row-reverse", flexWrap: "wrap", gap: 12 }, info: { width: "30%", alignItems: "flex-end" }, infoLabel: { color: "#9A9287", fontSize: 10 }, infoValue: { color: "#1F2937", fontSize: 12, fontWeight: "800", marginTop: 4, textAlign: "right" }, sectionTitle: { color: "#1F2937", fontSize: 16, fontWeight: "900", textAlign: "right" }, statusGrid: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8 }, statusButton: { width: "48%", borderWidth: 1, borderColor: "#E8E0D4", borderRadius: 12, padding: 11, flexDirection: "row-reverse", alignItems: "center", gap: 6 }, dot: { width: 8, height: 8, borderRadius: 4 }, statusText: { color: "#6B7280", fontSize: 10, fontWeight: "700", flex: 1, textAlign: "right" }, note: { backgroundColor: "#F1E7D4", borderRadius: 16, padding: 14 }, noteLabel: { color: "#9A661D", fontSize: 11, fontWeight: "900", textAlign: "right" }, noteText: { color: "#5F574D", fontSize: 13, lineHeight: 20, marginTop: 5, textAlign: "right" }, empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 30 }, link: { color: "#9A661D", marginTop: 12, fontWeight: "800" } });
