import { useEffect, useRef, useState } from "react";
import { AppState, Modal, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import * as LocalAuthentication from "expo-local-authentication";
import { useAppData } from "@/lib/app-store";
import { useColors } from "@/hooks/use-colors";

export function AppLock() {
  const colors = useColors(); const styles = makeStyles(colors); const { settings } = useAppData(); const [locked, setLocked] = useState(settings.pinEnabled || settings.biometricEnabled); const [pin, setPin] = useState(""); const backgroundAt = useRef<number | null>(null);
  useEffect(() => { setLocked(settings.pinEnabled || settings.biometricEnabled); }, [settings.pinEnabled, settings.biometricEnabled]);
  useEffect(() => { const subscription = AppState.addEventListener("change", async (nextState) => { if (nextState === "background") backgroundAt.current = Date.now(); if (nextState === "active" && backgroundAt.current && Date.now() - backgroundAt.current > 30_000 && (settings.pinEnabled || settings.biometricEnabled)) setLocked(true); if (nextState === "active") backgroundAt.current = null; }); return () => subscription.remove(); }, [settings.biometricEnabled, settings.pinEnabled]);
  useEffect(() => { if (locked && settings.biometricEnabled && Platform.OS !== "web") void unlockBiometric(); }, [locked, settings.biometricEnabled]);
  async function unlockBiometric() { const hasHardware = await LocalAuthentication.hasHardwareAsync(); const enrolled = await LocalAuthentication.isEnrolledAsync(); if (!hasHardware || !enrolled) return; const result = await LocalAuthentication.authenticateAsync({ promptMessage: "افتح Saber Electronics" }); if (result.success) setLocked(false); }
  function unlockPin() { if (settings.pin && pin === settings.pin) { setPin(""); setLocked(false); } }
  if (!locked) return null;
  return <Modal visible transparent animationType="fade"><View style={styles.overlay}><View style={styles.card}><Text style={styles.brand}>Saber Electronics</Text><Text style={styles.title}>التطبيق مقفل</Text><Text style={styles.subtitle}>أدخل رمز PIN للمتابعة أو استخدم البصمة.</Text>{settings.pinEnabled && <TextInput value={pin} onChangeText={setPin} onSubmitEditing={unlockPin} keyboardType="number-pad" secureTextEntry maxLength={6} placeholder="رمز PIN" placeholderTextColor={colors.muted} style={styles.input} textAlign="center" />}{settings.pinEnabled && <Pressable onPress={unlockPin} style={styles.button}><Text style={styles.buttonText}>فتح التطبيق</Text></Pressable>}{settings.biometricEnabled && <Pressable onPress={() => void unlockBiometric()} style={styles.secondary}><Text style={styles.secondaryText}>استخدام البصمة أو Face ID</Text></Pressable>}</View></View></Modal>;
}
function makeStyles(c: ReturnType<typeof useColors>) { return StyleSheet.create({ overlay: { flex: 1, backgroundColor: "rgba(4,15,27,0.78)", alignItems: "center", justifyContent: "center", padding: 24 }, card: { width: "100%", maxWidth: 380, backgroundColor: c.surface, borderRadius: 24, padding: 28, alignItems: "center", borderWidth: 1, borderColor: c.border }, brand: { color: c.primary, fontSize: 14, fontWeight: "900", marginBottom: 12 }, title: { color: c.foreground, fontSize: 26, fontWeight: "800", marginBottom: 8 }, subtitle: { color: c.muted, fontSize: 14, lineHeight: 22, textAlign: "center", marginBottom: 20 }, input: { width: "100%", borderWidth: 1, borderColor: c.border, borderRadius: 14, backgroundColor: c.background, padding: 14, fontSize: 20, marginBottom: 12, color: c.foreground }, button: { width: "100%", backgroundColor: c.primary, borderRadius: 14, padding: 15, alignItems: "center" }, buttonText: { color: "#FFF", fontSize: 15, fontWeight: "800" }, secondary: { padding: 14, marginTop: 6 }, secondaryText: { color: c.primary, fontWeight: "700", fontSize: 14 } }); }
