import { useState } from "react";
import type { ReactNode } from "react";
import { Alert, Modal, Pressable, ScrollView, Share, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import * as LocalAuthentication from "expo-local-authentication";
import * as Sharing from "expo-sharing";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

import { ScreenContainer } from "@/components/screen-container";
import { exportLocalBackup, importLocalBackup, useAppData } from "@/lib/app-store";
import { scheduleDeviceNotifications } from "@/lib/notifications";
import { useThemeContext } from "@/lib/theme-provider";
import { useColors } from "@/hooks/use-colors";
import { checkForUpdate, openUpdate, RELEASES_URL } from "@/lib/app-updates";

export default function SettingsScreen() {
  const colors = useColors();
  const { colorScheme, setColorScheme } = useThemeContext();
  const { devices, settings, updateSettings, resetAllData, reloadFromStorage } = useAppData();
  const [pinModal, setPinModal] = useState(false);
  const [pin, setPin] = useState(settings.pin);
  const themed = makeStyles(colors);

  async function toggleBiometric(value: boolean) { if (value && (!(await LocalAuthentication.hasHardwareAsync()) || !(await LocalAuthentication.isEnrolledAsync()))) { Alert.alert("البصمة غير متاحة", "فعّل البصمة أو Face ID في إعدادات الهاتف أولًا."); return; } await updateSettings({ biometricEnabled: value }); }
  async function toggleNotifications(key: "notifyReady" | "notifyOverdue", value: boolean) { await updateSettings({ [key]: value }); await scheduleDeviceNotifications(devices, { ready: key === "notifyReady" ? value : settings.notifyReady, overdue: key === "notifyOverdue" ? value : settings.notifyOverdue }); }
  async function savePin() { if (pin.length < 4) { Alert.alert("PIN قصير", "استخدم 4 أرقام على الأقل."); return; } await updateSettings({ pin, pinEnabled: true }); setPinModal(false); }
  async function checkUpdate() { const update = await checkForUpdate(); if (update) Alert.alert("يتوفر تحديث جديد", update.name, [{ text: "لاحقًا", style: "cancel" }, { text: "تنزيل", onPress: () => void openUpdate(update) }]); else Alert.alert("التطبيق محدث", "أنت تستخدم أحدث إصدار متاح."); }
  async function exportBackup() { const json = await exportLocalBackup(devices, settings); const uri = `${FileSystem.cacheDirectory}sabr-electronics-backup-${Date.now()}.json`; await FileSystem.writeAsStringAsync(uri, json, { encoding: FileSystem.EncodingType.UTF8 }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: "application/json", dialogTitle: "نسخة احتياطية Saber Electronics" }); else await Share.share({ message: json }); }
  async function restoreBackup() { const result = await DocumentPicker.getDocumentAsync({ type: "application/json", copyToCacheDirectory: true }); if (result.canceled) return; const json = await FileSystem.readAsStringAsync(result.assets[0].uri, { encoding: FileSystem.EncodingType.UTF8 }); await importLocalBackup(json); await reloadFromStorage(); Alert.alert("تمت الاستعادة", "تمت استعادة النسخة الاحتياطية بنجاح."); }
  const safe = (work: () => Promise<void>) => { void work().catch(() => Alert.alert("تعذر تنفيذ العملية", "تحقق من صلاحيات الهاتف وحاول مرة أخرى.")); };
  const toggle = { trackColor: { false: colors.border, true: "#4C6A83" }, thumbColor: colors.surface };
  return <ScreenContainer><ScrollView contentContainerStyle={themed.content}><View style={themed.brandRow}><View><Text style={themed.eyebrow}>SABER ELECTRONICS</Text><Text style={themed.title}>الإعدادات</Text><Text style={themed.subtitle}>الخصوصية، الثيم، التنبيهات والنسخ الاحتياطي.</Text></View><View style={themed.logo}><Text style={themed.logoText}>SE</Text></View></View>
    <Section title="المظهر" styles={themed}><SettingRow styles={themed} icon="contrast" title="الوضع الداكن" subtitle={colorScheme === "dark" ? "مفعّل — مريح للعين" : "غير مفعّل — الوضع الفاتح"} trailing={<Switch value={colorScheme === "dark"} onValueChange={(value) => setColorScheme(value ? "dark" : "light")} {...toggle} />} /></Section>
    <Section title="الحماية" styles={themed}><SettingRow styles={themed} icon="lock" title="رمز PIN" subtitle={settings.pinEnabled ? "مفعّل لحماية التطبيق" : "غير مفعّل"} trailing={<Switch value={settings.pinEnabled} onValueChange={(value) => value ? setPinModal(true) : void updateSettings({ pinEnabled: false, pin: "" })} {...toggle} />} /><SettingRow styles={themed} icon="fingerprint" title="البصمة أو Face ID" subtitle={settings.biometricEnabled ? "مفعّلة" : "غير مفعّلة"} trailing={<Switch value={settings.biometricEnabled} onValueChange={(value) => void toggleBiometric(value)} {...toggle} />} /></Section>
    <Section title="التنبيهات" styles={themed}><SettingRow styles={themed} icon="notifications-active" title="أجهزة جاهزة للتسليم" subtitle="تنبيه داخل الهاتف" trailing={<Switch value={settings.notifyReady} onValueChange={(value) => void toggleNotifications("notifyReady", value)} {...toggle} />} /><SettingRow styles={themed} icon="schedule" title="الأجهزة المتأخرة" subtitle="مقارنة بموعد التسليم المتوقع" trailing={<Switch value={settings.notifyOverdue} onValueChange={(value) => void toggleNotifications("notifyOverdue", value)} {...toggle} />} /><SettingRow styles={themed} icon="chat" title="WhatsApp عند الجاهزية" subtitle="فتح رسالة جاهزة عند تجهيز الجهاز" trailing={<Switch value={settings.whatsappReady} onValueChange={(value) => void updateSettings({ whatsappReady: value })} {...toggle} />} /><SettingRow styles={themed} icon="chat" title="WhatsApp عند التأخر" subtitle="فتح رسالة جاهزة عند تأخر التسليم" trailing={<Switch value={settings.whatsappOverdue} onValueChange={(value) => void updateSettings({ whatsappOverdue: value })} {...toggle} />} /></Section>
    <Section title="التحديثات والبيانات" styles={themed}><SettingRow styles={themed} icon="system-update" title="تحديث التطبيق" subtitle="فحص GitHub Releases دون حذف بياناتك" trailing={<Pressable onPress={() => safe(checkUpdate)} style={themed.inlineButton}><Text style={themed.inlineText}>فحص الآن</Text></Pressable>} /><SettingRow styles={themed} icon="public" title="إصدارات التطبيق" subtitle="فتح سجل الإصدارات العامة" trailing={<Pressable onPress={() => void import("expo-linking").then(({ openURL }) => openURL(RELEASES_URL))} style={themed.inlineButton}><Text style={themed.inlineText}>فتح</Text></Pressable>} /><SettingRow styles={themed} icon="backup" title="إنشاء نسخة احتياطية" subtitle="ملف JSON للسجلات والإعدادات" trailing={<Pressable onPress={() => safe(exportBackup)} style={themed.inlineButton}><Text style={themed.inlineText}>تصدير</Text></Pressable>} /><SettingRow styles={themed} icon="restore" title="استعادة نسخة احتياطية" subtitle="استبدال البيانات الحالية بالنسخة المختارة" trailing={<Pressable onPress={() => safe(restoreBackup)} style={themed.inlineButton}><Text style={themed.inlineText}>استعادة</Text></Pressable>} /><SettingRow styles={themed} icon="delete-outline" title="حذف بيانات التطبيق" subtitle="احذف كل السجلات نهائيًا" trailing={<Pressable onPress={() => Alert.alert("تأكيد الحذف", "هذا الإجراء لا يمكن التراجع عنه.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => void resetAllData() }])} style={themed.dangerButton}><Text style={themed.dangerText}>حذف</Text></Pressable>} /></Section>
    <View style={themed.footer}><Text style={themed.footerBrand}>Saber Electronics</Text><Text style={themed.footerText}>صيانة إلكترونيات متخصصة • البيانات محفوظة على هذا الهاتف فقط</Text></View>
  </ScrollView><Modal visible={pinModal} transparent animationType="fade"><View style={themed.overlay}><View style={themed.modal}><Text style={themed.modalTitle}>تعيين رمز PIN</Text><Text style={themed.modalText}>استخدم 4 إلى 6 أرقام لحماية التطبيق.</Text><TextInput value={pin} onChangeText={setPin} keyboardType="number-pad" secureTextEntry maxLength={6} placeholder="رمز PIN" placeholderTextColor={colors.muted} style={themed.pinInput} textAlign="center" /><View style={themed.modalActions}><Pressable onPress={() => setPinModal(false)} style={themed.cancel}><Text style={themed.cancelText}>إلغاء</Text></Pressable><Pressable onPress={() => void savePin()} style={themed.confirm}><Text style={themed.confirmText}>حفظ</Text></Pressable></View></View></View></Modal></ScreenContainer>;
}
function Section({ title, children, styles }: { title: string; children: ReactNode; styles: ReturnType<typeof makeStyles> }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.sectionCard}>{children}</View></View>; }
function SettingRow({ icon, title, subtitle, trailing, styles }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; subtitle: string; trailing: ReactNode; styles: ReturnType<typeof makeStyles> }) { return <View style={styles.row}><View style={styles.rowIcon}><MaterialIcons name={icon} size={20} color="#FFFFFF" /></View><View style={styles.rowText}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowSubtitle}>{subtitle}</Text></View>{trailing}</View>; }
function makeStyles(c: ReturnType<typeof useColors>) { return StyleSheet.create({ content: { padding: 20, paddingBottom: 36, direction: "rtl" }, brandRow: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", marginBottom: 22 }, logo: { width: 58, height: 58, borderRadius: 18, backgroundColor: c.primary, alignItems: "center", justifyContent: "center" }, logoText: { color: "#FFF", fontSize: 18, fontWeight: "900" }, eyebrow: { color: c.primary, fontSize: 12, fontWeight: "800", textAlign: "right" }, title: { color: c.foreground, fontSize: 29, fontWeight: "900", textAlign: "right", marginTop: 3 }, subtitle: { color: c.muted, fontSize: 13, textAlign: "right", marginTop: 6 }, section: { marginBottom: 18 }, sectionTitle: { color: c.foreground, fontSize: 16, fontWeight: "900", textAlign: "right", marginBottom: 9 }, sectionCard: { backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, borderRadius: 18, paddingHorizontal: 14 }, row: { minHeight: 67, flexDirection: "row-reverse", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: c.border }, rowIcon: { width: 35, height: 35, backgroundColor: c.primary, borderRadius: 11, alignItems: "center", justifyContent: "center" }, rowText: { flex: 1, alignItems: "flex-end" }, rowTitle: { color: c.foreground, fontSize: 13, fontWeight: "800", textAlign: "right" }, rowSubtitle: { color: c.muted, fontSize: 10, marginTop: 3, textAlign: "right" }, inlineButton: { paddingHorizontal: 10, paddingVertical: 7, backgroundColor: c.border, borderRadius: 9 }, inlineText: { color: c.foreground, fontSize: 11, fontWeight: "900" }, dangerButton: { paddingHorizontal: 10, paddingVertical: 7, backgroundColor: "#FCE9E7", borderRadius: 9 }, dangerText: { color: c.error, fontSize: 11, fontWeight: "900" }, footer: { alignItems: "center", paddingTop: 8 }, footerBrand: { color: c.foreground, fontSize: 14, fontWeight: "900" }, footerText: { color: c.muted, fontSize: 10, marginTop: 4 }, overlay: { flex: 1, backgroundColor: "rgba(4,15,27,.78)", justifyContent: "center", alignItems: "center", padding: 22 }, modal: { width: "100%", maxWidth: 360, backgroundColor: c.surface, borderRadius: 20, padding: 22 }, modalTitle: { color: c.foreground, fontSize: 20, fontWeight: "900", textAlign: "right" }, modalText: { color: c.muted, fontSize: 12, marginTop: 6, textAlign: "right" }, pinInput: { borderWidth: 1, borderColor: c.border, borderRadius: 13, padding: 13, fontSize: 22, color: c.foreground, marginTop: 16 }, modalActions: { flexDirection: "row-reverse", gap: 9, marginTop: 15 }, cancel: { flex: 1, alignItems: "center", padding: 13, borderRadius: 12, backgroundColor: c.border }, cancelText: { color: c.foreground, fontWeight: "800" }, confirm: { flex: 1, alignItems: "center", padding: 13, borderRadius: 12, backgroundColor: c.primary }, confirmText: { color: "#FFF", fontWeight: "800" } }); }
