import { useState } from "react";
import type { ReactNode } from "react";
import { Alert, Modal, Pressable, ScrollView, Share, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import * as LocalAuthentication from "expo-local-authentication";
import * as Sharing from "expo-sharing";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

import { ScreenContainer } from "@/components/screen-container";
import { exportLocalBackup, importLocalBackup, useAppData } from "@/lib/app-store";
import { scheduleDeviceNotifications } from "@/lib/notifications";

export default function SettingsScreen() {
  const { devices, settings, updateSettings, resetAllData, reloadFromStorage } = useAppData();
  const [pinModal, setPinModal] = useState(false);
  const [pin, setPin] = useState(settings.pin);

  async function toggleBiometric(value: boolean) {
    if (value) {
      const available = await LocalAuthentication.hasHardwareAsync();
      const enrolled = await LocalAuthentication.isEnrolledAsync();
      if (!available || !enrolled) { Alert.alert("البصمة غير متاحة", "فعّل البصمة أو Face ID في إعدادات الهاتف أولًا."); return; }
    }
    await updateSettings({ biometricEnabled: value });
  }
  async function toggleNotifications(key: "notifyReady" | "notifyOverdue", value: boolean) {
    await updateSettings({ [key]: value });
    await scheduleDeviceNotifications(devices, { ready: key === "notifyReady" ? value : settings.notifyReady, overdue: key === "notifyOverdue" ? value : settings.notifyOverdue });
  }
  async function savePin() { if (pin.length < 4) { Alert.alert("PIN قصير", "استخدم 4 أرقام على الأقل."); return; } await updateSettings({ pin, pinEnabled: true }); setPinModal(false); }
  async function exportBackup() { const json = await exportLocalBackup(devices, settings); const uri = `${FileSystem.cacheDirectory}sabr-electronics-backup-${Date.now()}.json`; await FileSystem.writeAsStringAsync(uri, json, { encoding: FileSystem.EncodingType.UTF8 }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: "application/json", dialogTitle: "نسخة احتياطية صبر إلكترونكس" }); else await Share.share({ message: json }); }
  async function restoreBackup() { const result = await DocumentPicker.getDocumentAsync({ type: "application/json", copyToCacheDirectory: true }); if (result.canceled) return; const json = await FileSystem.readAsStringAsync(result.assets[0].uri, { encoding: FileSystem.EncodingType.UTF8 }); await importLocalBackup(json); await reloadFromStorage(); Alert.alert("تمت الاستعادة", "تمت استعادة النسخة الاحتياطية بنجاح."); }
  const safe = (work: () => Promise<void>) => { void work().catch(() => Alert.alert("تعذر تنفيذ العملية", "تحقق من صلاحيات الهاتف وحاول مرة أخرى.")); };
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>تخصيص وحماية</Text><Text style={styles.title}>الإعدادات</Text><Text style={styles.subtitle}>تحكم بالخصوصية والتنبيهات والنسخ الاحتياطي.</Text>
    <Section title="الحماية"><SettingRow icon="lock" title="رمز PIN" subtitle={settings.pinEnabled ? "مفعّل لحماية التطبيق" : "غير مفعّل"} trailing={<Switch value={settings.pinEnabled} onValueChange={(value) => value ? setPinModal(true) : void updateSettings({ pinEnabled: false, pin: "" })} trackColor={{ false: "#DDD5C9", true: "#D7B477" }} thumbColor={settings.pinEnabled ? "#9A661D" : "#FFF"} />} /><SettingRow icon="fingerprint" title="البصمة أو Face ID" subtitle={settings.biometricEnabled ? "مفعّلة" : "غير مفعّلة"} trailing={<Switch value={settings.biometricEnabled} onValueChange={(value) => void toggleBiometric(value)} trackColor={{ false: "#DDD5C9", true: "#D7B477" }} thumbColor={settings.biometricEnabled ? "#9A661D" : "#FFF"} />} /></Section>
    <Section title="التنبيهات"><SettingRow icon="notifications-active" title="أجهزة جاهزة للتسليم" subtitle="تنبيه داخل الهاتف" trailing={<Switch value={settings.notifyReady} onValueChange={(value) => void toggleNotifications("notifyReady", value)} trackColor={{ false: "#DDD5C9", true: "#D7B477" }} thumbColor={settings.notifyReady ? "#9A661D" : "#FFF"} />} /><SettingRow icon="schedule" title="الأجهزة المتأخرة" subtitle="مقارنة بموعد التسليم المتوقع" trailing={<Switch value={settings.notifyOverdue} onValueChange={(value) => void toggleNotifications("notifyOverdue", value)} trackColor={{ false: "#DDD5C9", true: "#D7B477" }} thumbColor={settings.notifyOverdue ? "#9A661D" : "#FFF"} />} /><SettingRow icon="chat" title="رسالة WhatsApp عند الجاهزية" subtitle="يفتح WhatsApp برسالة جاهزة" trailing={<Switch value={settings.whatsappReady} onValueChange={(value) => void updateSettings({ whatsappReady: value })} trackColor={{ false: "#DDD5C9", true: "#D7B477" }} thumbColor={settings.whatsappReady ? "#9A661D" : "#FFF"} />} /><SettingRow icon="chat" title="رسالة WhatsApp عند التأخر" subtitle="تفعيل اختياري لكل حالة" trailing={<Switch value={settings.whatsappOverdue} onValueChange={(value) => void updateSettings({ whatsappOverdue: value })} trackColor={{ false: "#DDD5C9", true: "#D7B477" }} thumbColor={settings.whatsappOverdue ? "#9A661D" : "#FFF"} />} /></Section>
    <Section title="البيانات"><SettingRow icon="backup" title="إنشاء نسخة احتياطية" subtitle="ملف JSON يشمل السجلات والإعدادات" trailing={<Pressable onPress={() => safe(exportBackup)} style={styles.inlineButton}><Text style={styles.inlineText}>تصدير</Text></Pressable>} /><SettingRow icon="restore" title="استعادة نسخة احتياطية" subtitle="استبدال البيانات الحالية بالنسخة المختارة" trailing={<Pressable onPress={() => safe(restoreBackup)} style={styles.inlineButton}><Text style={styles.inlineText}>استعادة</Text></Pressable>} /><SettingRow icon="delete-outline" title="حذف بيانات التطبيق" subtitle="احذف كل السجلات نهائيًا" trailing={<Pressable onPress={() => Alert.alert("تأكيد الحذف", "هذا الإجراء لا يمكن التراجع عنه.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => void resetAllData() }])} style={styles.dangerButton}><Text style={styles.dangerText}>حذف</Text></Pressable>} /></Section>
    <View style={styles.footer}><Text style={styles.footerBrand}>صبر إلكترونكس</Text><Text style={styles.footerText}>نسخة محلية أولى • البيانات محفوظة على هذا الهاتف فقط</Text></View>
  </ScrollView><Modal visible={pinModal} transparent animationType="fade"><View style={styles.overlay}><View style={styles.modal}><Text style={styles.modalTitle}>تعيين رمز PIN</Text><Text style={styles.modalText}>استخدم 4 إلى 6 أرقام لحماية التطبيق.</Text><TextInput value={pin} onChangeText={setPin} keyboardType="number-pad" secureTextEntry maxLength={6} placeholder="رمز PIN" placeholderTextColor="#A69C90" style={styles.pinInput} textAlign="center" /><View style={styles.modalActions}><Pressable onPress={() => setPinModal(false)} style={styles.cancel}><Text style={styles.cancelText}>إلغاء</Text></Pressable><Pressable onPress={() => void savePin()} style={styles.confirm}><Text style={styles.confirmText}>حفظ</Text></Pressable></View></View></View></Modal></ScreenContainer>;
}
function Section({ title, children }: { title: string; children: ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.sectionCard}>{children}</View></View>; }
function SettingRow({ icon, title, subtitle, trailing }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; subtitle: string; trailing: ReactNode }) { return <View style={styles.row}><View style={styles.rowIcon}><MaterialIcons name={icon} size={20} color="#9A661D" /></View><View style={styles.rowText}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowSubtitle}>{subtitle}</Text></View>{trailing}</View>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 36, direction: "rtl" }, eyebrow: { color: "#9A661D", fontSize: 12, fontWeight: "800", textAlign: "right" }, title: { color: "#1F2937", fontSize: 29, fontWeight: "900", textAlign: "right", marginTop: 3 }, subtitle: { color: "#80776B", fontSize: 13, textAlign: "right", marginTop: 6, marginBottom: 18 }, section: { marginBottom: 18 }, sectionTitle: { color: "#1F2937", fontSize: 16, fontWeight: "900", textAlign: "right", marginBottom: 9 }, sectionCard: { backgroundColor: "#FFF", borderWidth: 1, borderColor: "#EEE7DC", borderRadius: 18, paddingHorizontal: 14 }, row: { minHeight: 67, flexDirection: "row-reverse", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: "#F2EEE8" }, rowIcon: { width: 35, height: 35, backgroundColor: "#F6EEDC", borderRadius: 11, alignItems: "center", justifyContent: "center" }, rowText: { flex: 1, alignItems: "flex-end" }, rowTitle: { color: "#374151", fontSize: 13, fontWeight: "800", textAlign: "right" }, rowSubtitle: { color: "#9A9287", fontSize: 10, marginTop: 3, textAlign: "right" }, inlineButton: { paddingHorizontal: 10, paddingVertical: 7, backgroundColor: "#F6EEDC", borderRadius: 9 }, inlineText: { color: "#9A661D", fontSize: 11, fontWeight: "900" }, dangerButton: { paddingHorizontal: 10, paddingVertical: 7, backgroundColor: "#FCE9E7", borderRadius: 9 }, dangerText: { color: "#C25B56", fontSize: 11, fontWeight: "900" }, footer: { alignItems: "center", paddingTop: 8 }, footerBrand: { color: "#9A661D", fontSize: 14, fontWeight: "900" }, footerText: { color: "#AAA094", fontSize: 10, marginTop: 4 }, overlay: { flex: 1, backgroundColor: "rgba(17,24,39,.7)", justifyContent: "center", alignItems: "center", padding: 22 }, modal: { width: "100%", maxWidth: 360, backgroundColor: "#FFFDF9", borderRadius: 20, padding: 22 }, modalTitle: { color: "#1F2937", fontSize: 20, fontWeight: "900", textAlign: "right" }, modalText: { color: "#7C7367", fontSize: 12, marginTop: 6, textAlign: "right" }, pinInput: { borderWidth: 1, borderColor: "#E4DCCE", borderRadius: 13, padding: 13, fontSize: 22, color: "#1F2937", marginTop: 16 }, modalActions: { flexDirection: "row-reverse", gap: 9, marginTop: 15 }, cancel: { flex: 1, alignItems: "center", padding: 13, borderRadius: 12, backgroundColor: "#F1EEE9" }, cancelText: { color: "#6B7280", fontWeight: "800" }, confirm: { flex: 1, alignItems: "center", padding: 13, borderRadius: 12, backgroundColor: "#9A661D" }, confirmText: { color: "#FFF", fontWeight: "800" } });
